"""initial_schema

Revision ID: 6cfd93685f71
Revises: 
Create Date: 2026-09-20 11:14:04.736716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfd93685f71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_topic'), 'sessions', ['topic'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('session_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('understanding_score', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.String(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('high_priority_learning_gaps', sa.JSON(), nullable=False),
    sa.Column('medium_priority_learning_gaps', sa.JSON(), nullable=False),
    sa.Column('low_priority_learning_gaps', sa.JSON(), nullable=False),
    sa.Column('misconceptions_detected', sa.JSON(), nullable=False),
    sa.Column('concepts_mastered', sa.JSON(), nullable=False),
    sa.Column('teacher_interventions_required', sa.Integer(), nullable=False),
    sa.Column('difficulty_achieved', sa.Integer(), nullable=False),
    sa.Column('personalized_roadmap', sa.JSON(), nullable=False),
    sa.Column('recommended_exercises', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_reports_session_id'), 'session_reports', ['session_id'], unique=False)
    op.create_table('session_states',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('current_mode', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('active_concept', sa.String(), nullable=False),
    sa.Column('current_question_id', sa.UUID(), nullable=True),
    sa.Column('interrupted_question_id', sa.UUID(), nullable=True),
    sa.Column('consecutive_strong_answers', sa.Integer(), nullable=False),
    sa.Column('consecutive_weak_answers', sa.Integer(), nullable=False),
    sa.Column('unresolved_misconceptions', sa.JSON(), nullable=False),
    sa.Column('mastered_concepts', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_states_session_id'), 'session_states', ['session_id'], unique=False)
    op.create_table('turn_evaluations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('correctness', sa.Float(), nullable=False),
    sa.Column('clarity', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('stuck_probability', sa.Float(), nullable=False),
    sa.Column('misconceptions', sa.JSON(), nullable=False),
    sa.Column('missing_concepts', sa.JSON(), nullable=False),
    sa.Column('undefined_terms', sa.JSON(), nullable=False),
    sa.Column('mastered_concepts', sa.JSON(), nullable=False),
    sa.Column('knowledge_gap', sa.Text(), nullable=True),
    sa.Column('recommended_strategy', sa.String(), nullable=False),
    sa.Column('recommended_difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_turn_evaluations_message_id'), 'turn_evaluations', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_evaluations_message_id'), table_name='turn_evaluations')
    op.drop_table('turn_evaluations')
    op.drop_index(op.f('ix_session_states_session_id'), table_name='session_states')
    op.drop_table('session_states')
    op.drop_index(op.f('ix_session_reports_session_id'), table_name='session_reports')
    op.drop_table('session_reports')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_topic'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
