from enum import Enum

class LearningMode(str, Enum):
    STUDENT = "STUDENT"
    TEACHER = "TEACHER"
    EVALUATOR = "EVALUATOR"

class InputType(str, Enum):
    TEXT = "TEXT"
    VOICE = "VOICE"

class SessionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"

class SourceType(str, Enum):
    GENERAL = "GENERAL"
    DOCUMENT = "DOCUMENT"

class MasteryLevel(str, Enum):
    BEGINNER = "BEGINNER"
    DEVELOPING = "DEVELOPING"
    PROFICIENT = "PROFICIENT"
    MASTERY = "MASTERY"

class LearningStrategy(str, Enum):
    ASK_FOUNDATION = "ASK_FOUNDATION"
    PROBE_WHY = "PROBE_WHY"
    PROBE_HOW = "PROBE_HOW"
    CLARIFY_TERM = "CLARIFY_TERM"
    PROBE_MISSING_CONCEPT = "PROBE_MISSING_CONCEPT"
    CHALLENGE_MISCONCEPTION = "CHALLENGE_MISCONCEPTION"
    INCREASE_DIFFICULTY = "INCREASE_DIFFICULTY"
    TEACH_GAP = "TEACH_GAP"
    VERIFY_UNDERSTANDING = "VERIFY_UNDERSTANDING"
    RESTORE_INTERRUPTED_QUESTION = "RESTORE_INTERRUPTED_QUESTION"
    OFFER_TERMINATION = "OFFER_TERMINATION"
    GENERATE_REPORT = "GENERATE_REPORT"
